################################################################################
#
# kf5-extra-cmake-modules
#
################################################################################

KF6_EXTRA_CMAKE_MODULES_VERSION = $(KF6_VERSION)
KF6_EXTRA_CMAKE_MODULES_SITE = $(KF6_SITE)
KF6_EXTRA_CMAKE_MODULES_SOURCE = extra-cmake-modules-$(KF6_EXTRA_CMAKE_MODULES_VERSION).tar.xz
KF6_EXTRA_CMAKE_MODULES_LICENSE = BSD-3-Clause
KF6_EXTRA_CMAKE_MODULES_LICENSE_FILES = COPYING-CMAKE-SCRIPTS

KF6_EXTRA_CMAKE_MODULES_DEPENDENCIES = host-pkgconf
KF6_EXTRA_CMAKE_MODULES_INSTALL_STAGING = YES
KF6_EXTRA_CMAKE_MODULES_INSTALL_TARGET = NO

KF6_EXTRA_CMAKE_MODULES_CONF_OPTS += \
	-DBUILD_HTML_DOCS=OFF \
	-DBUILD_MAN_DOCS=OFF \
	-DBUILD_QTHELP_DOCS=OFF

$(eval $(cmake-package))
