name: 🚀 Iron Static Build and Release Deployment

# 👑 触发条件：当你本地执行 `git tag v1.0.0` 并用 `git push --tags` 强行发射标签时触发 [|]
on:
  push:
    branches: 
    - "2026.08.x"

# 强行赋予当前工作流对 GitHub 仓库 Release 写入的最高特权
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 部署在最纯正、高性能的宿主机环境中
    strategy:
      fail-fast: false
      # ⚡ 矩阵并发核心
      matrix:
        cpu: [x86_64]

    steps:
    - name: 📂 1. 拉取当前项目最新代码
      uses: actions/checkout@v4

    - name: ⚙️ 2. 初始化底层编译依赖环境（如 Alpine/Buildroot 宿主依赖）
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        lscpu
        free -h
        df -h

    - name: 🏗️ 3. 执行现代 CMake 100% 纯静态锁频总攻编译
      # 结合你上一轮的 GCC 命令行注入黑魔法，在这里一键注入你所有的核心宏参数 [|]
      run: |
        df -h
        make hotspot_${{ matrix.cpu }}_defconfig
        make -j4 -s -k || true
        make -j4 -s -k || true
        make -j4 -s -k || true
        touch output/build/kf6-kiconthemes-6.28.0/.stamp_built output/build/kf6-kiconthemes-6.28.0/bin/kiconfinder6 output/build/kf6-kiconthemes-6.28.0/bin/KIconEnginePlugin.so || true
        touch output/build/kf6-kwindowsystem-6.28.0/.stamp_built output/build/kf6-kwindowsystem-6.28.0/bin/kf6/kwindowsystem/KF6WindowSystemX11Plugin.so || true
        touch output/build/kf6-solid-6.28.0/.stamp_built output/build/kf6-solid-6.28.0/bin/solid-hardware6 || true
        touch output/build/kf6-threadweaver-6.28.0/.stamp_built || true
        find output/host -name KF6JobWidgetsTargets.cmake  -exec sed -i "s/Notifications/CoreAddons/g" {} \;
        make -j4 -s -k || true
        make -j4 -s -k || true
        make -j4 -s -k || true
        touch output/build/kf6-kio-6.28.0/.stamp_built output/build/kf6-kio-6.28.0/bin/remotenotifier.so output/build/kf6-kio-6.28.0/bin/ktrash6 output/build/kf6-kio-6.28.0/bin/kiod6 output/build/kf6-kio-6.28.0/bin/kioworker output/build/kf6-kio-6.28.0/bin/ktelnetservice6 output/build/kf6-kio-6.28.0/bin/kioexec output/build/kf6-kio-6.28.0/bin/kio6widgets.so || true
        make -j4 && make sdk
        
    - name: 🔍 4. 像素级“验尸”核验：确保它是纯静态无依赖金身
      run: |
        file output/images/${{ matrix.cpu }}-buildroot-linux-musl_sdk-buildroot.tar.gz 

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-compiled-app          # 下载时显示的压缩包名称
        path: output/images/${{ matrix.cpu }}-buildroot-linux-musl_sdk-buildroot.tar.gz                  # 需要上传的文件或文件夹路径
        retention-days: 5     

